//
//  SearchModels.swift
//  Viewer
//
//  Created by Dario Suarez on 13/06/2019.
//  Copyright (c) 2019 Dario Suarez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchScene {
    // MARK: Use cases
    enum Search {
        struct Request {
            let query: String
        }
        struct Response {
            let result: SearchResult?
        }
        struct ViewModel {
            let result: [SearchItemResultViewModel]
        }
    }
}


struct SearchItemResultViewModel: Equatable {
    let name: String
    let price: String
    let image: String
    
    static func ==(lhs: SearchItemResultViewModel, rhs: SearchItemResultViewModel) -> Bool {
        return lhs.name == rhs.name &&
        lhs.price == rhs.price &&
        lhs.image == rhs.image
    }
}

enum NetworkingError {
    struct Response {
        let message: String
    }
    struct ViewModel {
        let title: String
        let detail: String
    }
}

struct NoInternetConnectionViewModel {
    let title: String
    let detail: String
}
