//
//  SearchRouter.swift
//  Viewer
//
//  Created by Dario Suarez on 13/06/2019.
//  Copyright (c) 2019 Dario Suarez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
    func navigateToDetail()
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?

    func navigateToDetail() {
        guard let destinationVC = UIStoryboard(name: "ItemDetailVC", bundle: nil).instantiateInitialViewController() as? ItemDetailViewController else { return }
        var destinationDS = destinationVC.router!.dataStore!
        passDataToItemDetail(source: dataStore!,
                             destination: &destinationDS)
        viewController?.show(destinationVC, sender: nil)
    }

    // MARK: Passing data

    func passDataToItemDetail(source: SearchDataStore,
                              destination: inout ItemDetailDataStore) {
        guard let row = viewController?.tableView.indexPathForSelectedRow?.row else { return }
        destination.item = source.searchResult!.results![row]
    }
}
