//
//  ItemDetailWorker.swift
//  Viewer
//
//  Created by Dario Suarez on 29/06/2019.
//  Copyright (c) 2019 Dario Suarez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemDetailWorkerProtocol {
    func itemDetail(_ id: String,
                    success: @escaping (ItemDescription?) -> Void,
                    failure: @escaping (ViewerError) -> Void)
}

class ItemDetailWorker: ItemDetailWorkerProtocol {
    
    var networking: Networking
    
    init(networking: Networking) {
        self.networking = networking
    }
    
    func itemDetail(_ id: String,
                    success: @escaping (ItemDescription?) -> Void,
                    failure: @escaping (ViewerError) -> Void) {
        let request = ItemService.getDescription(id: id).urlRequest
        networking.call(urlRequest: request,
                        decodingType: ItemDescription.self) { (result) in
                            switch result {
                            case .empty:
                                success(nil)
                            case .success(let obj):
                                success(obj)
                            case .failure(let err):
                                failure(err)
                            }
        }
    }
}
