//
//  ItemDetailPresenter.swift
//  Viewer
//
//  Created by Dario Suarez on 16/06/2019.
//  Copyright (c) 2019 Dario Suarez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemDetailPresentationLogic {
    func presentItem(response: ItemDetail.Load.Response)
}

class ItemDetailPresenter: ItemDetailPresentationLogic {
    weak var viewController: ItemDetailDisplayLogic?

    func presentItem(response: ItemDetail.Load.Response) {
        let vm = ItemDetail.Load.ViewModel(name: response.item.title ?? "",
                                           type: response.item.condition ?? "",
                                           image: response.item.thumbnail ?? "",
                                           price: "$\(response.item.price ?? 0.0)",
                                           desc: response.desc?.plainText ?? "Descripcion no disponible")
        viewController?.displayItem(viewModel: vm)
    }
}
