//
//  ItemDetailModels.swift
//  Viewer
//
//  Created by Dario Suarez on 16/06/2019.
//  Copyright (c) 2019 Dario Suarez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ItemDetail {
    // MARK: Use cases

    enum Load {
        struct Response {
            let item: SearchResultItem
            let desc: ItemDescription?
        }
        struct ViewModel {
            let name: String
            let type: String
            let image: String
            let price: String
            let desc: String
        }
    }
}
