//
//  ItemDetailRouter.swift
//  Viewer
//
//  Created by Dario Suarez on 16/06/2019.
//  Copyright (c) 2019 Dario Suarez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ItemDetailRoutingLogic {
}

protocol ItemDetailDataPassing {
    var dataStore: ItemDetailDataStore? { get }
}

class ItemDetailRouter: NSObject, ItemDetailRoutingLogic, ItemDetailDataPassing {
    weak var viewController: ItemDetailViewController?
    var dataStore: ItemDetailDataStore?
}
